logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/
  instance:
    prefer-ip-address: true

aaa:
  bbb:
    ccc: 123456
