spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BatchTest?serverTimezone=UTC
    username: liang
    password: passw0rd

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/
  instance:
    prefer-ip-address: true

user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true
